"""Token/cost savings dashboard (Optimization visibility).

The original design doc had a whole panel titled "Why this saves
tokens" - Domain Gate, Evidence Gate, and caching all exist specifically
to avoid LLM calls, but none of those savings were ever actually shown
anywhere. This module makes them visible: a handful of counters,
incremented at the exact points in the codebase where a call was
avoided or a cheaper tier was used instead of the expensive one.

App-wide, not per-user: threading a user_id through every call site
(including deep inside services/consensus.py, which doesn't currently
take one) would be a much more invasive change for a single dashboard
feature. An app-wide "here's how much this architecture is saving
overall" number is still honest and still the useful thing to see.

In-memory only, same trade-off as services/cache.py and
services/rate_limiter.py - a restart resets the counters to zero rather
than losing anything that can't be regenerated by continuing to use the
app.
"""

from __future__ import annotations

import threading
import time

_lock = threading.Lock()
_started_at = time.time()

_counters: dict[str, int] = {
    "cache_hits": 0,
    "cache_misses": 0,
    "domain_gate_rejections": 0,
    "evidence_gate_rejections": 0,
    "consensus_calls_fast": 0,
    "consensus_calls_full": 0,
}

# Rough, clearly-labeled ESTIMATE, not a measurement - this codebase
# doesn't track exact prompt/completion token counts per call today,
# so instead of fabricating false precision, an average is applied
# consistently and the dashboard labels it as an estimate throughout.
# ~1500 tokens is a reasonable middle-of-the-road figure for this app's
# prompts (data summaries / retrieved excerpts + a few paragraphs back).
ESTIMATED_TOKENS_PER_AVOIDED_CALL = 1500
# A full-tier consensus call makes 3 provider calls (Groq + NVIDIA +
# MiniMax) vs. fast-tier's 1 (with fallback only on failure) - so using
# fast tier instead of full for a given step saves roughly 2x that call's
# token cost, on average.
FULL_TIER_CALL_MULTIPLIER = 3
FAST_TIER_CALL_MULTIPLIER = 1


def record_cache_hit() -> None:
    with _lock:
        _counters["cache_hits"] += 1


def record_cache_miss() -> None:
    with _lock:
        _counters["cache_misses"] += 1


def record_domain_gate_rejection() -> None:
    with _lock:
        _counters["domain_gate_rejections"] += 1


def record_evidence_gate_rejection() -> None:
    with _lock:
        _counters["evidence_gate_rejections"] += 1


def record_consensus_call(tier: str) -> None:
    with _lock:
        if tier == "fast":
            _counters["consensus_calls_fast"] += 1
        elif tier == "full":
            _counters["consensus_calls_full"] += 1


def get_stats() -> dict:
    with _lock:
        counters = dict(_counters)

    calls_avoided = counters["cache_hits"] + counters["domain_gate_rejections"] + counters["evidence_gate_rejections"]
    estimated_tokens_saved_from_avoided_calls = calls_avoided * ESTIMATED_TOKENS_PER_AVOIDED_CALL

    fast_calls = counters["consensus_calls_fast"]
    estimated_tokens_saved_from_fast_tier = (
        fast_calls * (FULL_TIER_CALL_MULTIPLIER - FAST_TIER_CALL_MULTIPLIER) * ESTIMATED_TOKENS_PER_AVOIDED_CALL
    )

    total_cache_lookups = counters["cache_hits"] + counters["cache_misses"]
    cache_hit_rate = round(counters["cache_hits"] / total_cache_lookups, 3) if total_cache_lookups else None

    return {
        "since": _started_at,
        "counters": counters,
        "cache_hit_rate": cache_hit_rate,
        "total_calls_avoided": calls_avoided,
        "estimated_tokens_saved": {
            "from_avoided_calls": estimated_tokens_saved_from_avoided_calls,
            "from_fast_tier_usage": estimated_tokens_saved_from_fast_tier,
            "total": estimated_tokens_saved_from_avoided_calls + estimated_tokens_saved_from_fast_tier,
            "methodology": (
                f"Estimate only, not a measurement: assumes ~{ESTIMATED_TOKENS_PER_AVOIDED_CALL} tokens per "
                "avoided LLM call, and that fast-tier calls save roughly 2x a call's tokens versus the "
                "3-provider full-tier consensus they replaced."
            ),
        },
    }


def reset_all() -> None:
    """Test/debug helper - zeroes every counter."""
    global _started_at
    with _lock:
        for key in _counters:
            _counters[key] = 0
        _started_at = time.time()
